import { Layout, Menu } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import Link from "next/link";
import styles from './layout.module.scss'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { FC, ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children: ReactNode[]
}

export const metadata: Metadata = {
  title: "Практическое задание",
  description: "Generated by create next app",
};

const items = [
  { key: 0, label: <Link href="/">Home</Link> },
  { key: 1, label: <Link href="posts">Posts</Link> },
  { key: 2, label: <Link href="albums">Albums</Link> },
  { key: 3, label: <Link href="todos">Todos</Link> },
];

const RootLayout: FC<Props> = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Layout className={styles.root}>
            <Header className={styles.header}>
              <Menu
                theme="dark"
                mode="horizontal"
                defaultSelectedKeys={["0"]}
                items={items}
                style={{ flex: 1, minWidth: 0 }}
              />
            </Header>
            <Content className={styles.content}>
              {children}
            </Content>
            <Footer className={styles.footer}>Footer</Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
};

export default RootLayout

